import Head from 'next/head'
import Image from 'next/image'

import {useTheme} from 'next-themes'
import Link from 'next/link'

export default function Inscrever() {
  const {theme, setTheme} = useTheme()

  return (
    <div>
      <Head>
        <title> Sintaxy Academy </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="bg-white dark:bg-slate-800 relative max-w-7xl mx-auto px-4 focus:outline-none sm:px-3 md:px-5">
          <div className="py-3 md:py-10 text-center">
            <div className="">
              <Link href="/">
              <a className="text-gray-300 underline"> Voltar </a>
              </Link>
            </div>
            <h2 className="text-3xl mt-5"> Faça Sua Incrição </h2>
          </div>

          <div>
            <iframe 
            src="https://docs.google.com/forms/d/e/1FAIpQLSdrd9lDqaZh6YWFbKYyLhIcsAKaxWBaza5xjszOEo66FXcNAQ/viewform?embedded=true" 
            width="100%" 
            height="4620" 
            frameBorder="0" 
            marginHeight="0" 
            marginWidth="0">A carregar…</iframe>
          </div>
          
        </div>

        <footer className="pt-10 border-t border-gray-700 dark:bg-slate-800  bg-gray-100 py-5">
          <div className="text-center text-md md:text-base relative max-w-7xl mx-auto px-4 focus:outline-none sm:px-3 md:px-5">
            <span className="dark:text-gray-100 text-center"> &copy; 2022 <a className="text-[#C21B78]" rel="noreferrer" href="https://sintaxy.com/" target="_blank"> Sintaxy </a> Todos os direitos reservados. </span>
          </div>
        </footer>

      </div>
    </div>
  )
}
